=== JDBC driver

Micronaut Data JDBC requires that an appropriate `java.sql.DataSource` bean is configured.

You can either do this manually or use the https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc[Micronaut JDBC] module which provides out-of-the-box support for configuring connection pooling with either Tomcat JDBC, Hikari, Commons DBCP or Oracle UCP.

=== SQL Logging

You can enable SQL logging by enabling trace logging for the `io.micronaut.data.query` logger. For example in `logback.xml`:

.Enabling SQL Query Logging
[source,xml]
----
<logger name="io.micronaut.data.query" level="trace" />
----

=== Creating the Schema

To create the database schema it is recommended you pair Micronaut Data with a SQL migration tool such as https://micronaut-projects.github.io/micronaut-flyway/latest/guide/index.html[Flyway] or https://micronaut-projects.github.io/micronaut-liquibase/latest/guide/index.html[Liquibase].

SQL migration tools provide more complete support for creating and evolving your schema across a range of databases.

If you want to quickly test out Micronaut Data then you can set the `schema-generate` option of the data source to `create-drop` as well as the appropriate schema name:

NOTE: Most of the database migration tools use JDBC driver to make DB changes. If you use R2DBC you would need to separately configure JDBC data source.

.Using `schema-generate`
[configuration]
----
include::doc-examples/jdbc-example-java/src/main/resources/application.yml[]
----

The `schema-generate` option is currently only recommended for simple applications, testing and demos and is not considered production-ready. The dialect set in configuration is the dialect that will be used to generate the schema.

=== Setting the Dialect

As seen in the configuration above you should also configure the dialect. Although queries are precomputed in the repository some cases (like pagination) still require the dialect to specify. The following table summarizes the supported dialects:

.Supported JDBC / R2DBC Dialects
[cols=2*]
|===
|*Dialect*
|*Description*

|api:data.model.query.builder.sql.Dialect#H2[]
|The H2 database (typically used for in-memory testing)

|api:data.model.query.builder.sql.Dialect#MYSQL[]
|MySQL 5.5 or above

|api:data.model.query.builder.sql.Dialect#POSTGRES[]
|Postgres 9.5 or above

|api:data.model.query.builder.sql.Dialect#SQL_SERVER[]
|SQL Server 2012 or above

|api:data.model.query.builder.sql.Dialect#ORACLE[]
|Oracle 12c or above

|===

IMPORTANT: The dialect setting in configuration does *not* replace the need to ensure the correct dialect is set at the repository. If the dialect is H2 in configuration, the repository should have `@JdbcRepository(dialect = Dialect.H2)` / `@R2dbcRepository(dialect = Dialect.H2)`. Because repositories are computed at compile time, the configuration value is not known at that time.

=== Connection client info tracing

In order to trace SQL calls using `java.sql.Connection.setClientInfo(String, String)` method, you can
annotate a repository with the ann:data.connection.annotation.ClientInfo[] annotation or ann:data.connection.annotation.ClientInfo.Attribute[] for individual client info.

Note that the ann:data.connection.annotation.ClientInfo.Attribute[] annotation can be used on either the class or the method, thus allowing customization of the  module or action individually.

For Oracle database, following attributes can be set to the connection client info: `OCSID.MODULE`, `OCSID.ACTION` and `OCSID.CLIENTID` and provided in ann:data.connection.annotation.ClientInfo.Attribute[].
If some of these attributes are not provided then Micronaut Data Jdbc is going to populate values automatically for Oracle connections:

*** `OCSID.MODULE` will get the value of the class name where annotation `@ClientInfo.Attribute` is added (usually Micronaut Data repository class)
*** `OCSID.ACTION` will get the value of the method name which is annotated with `@ClientInfo.Attribute` annotation
*** `OCSID.CLIENTID` will get the value of the Micronaut application name, if configured

Please note this feature is currently supported only for Oracle database connections. In order to enable Oracle JDBC connection client info to be set,
you need to specify the configuration property `datasources.<datasource-name>.enable-oracle-client-info=true` on a per datasource basis.

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-data-jdbc-repository.html[Access a Database with Micronaut Data JDBC] to learn more.

